apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  namespace: "finociate-dev"
  labels: 
    app: "mongo-db"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /run/desktop/mnt/host/c/Workspace/finociate-mongo
